# namespace: wordpress-flche
wordpress:
  replicaCount: 1
  wordpressPassword: P@$$w0rd!
  service:  
    type: ClusterIP
  persistence:
    enabled: true
    storageClass: managed-csi
    accessModes: [ ReadWriteOnce ]
    size: 64Gi    
  mariadb:    
    primary:
      persistence:
        storageClass: managed-csi
        accessModes: [ ReadWriteOnce ]
        size: 32Gi
      