# namespace: cattle-system
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt 
    kubernetes.io/ingress.class: azure/application-gateway  
    appgw.ingress.kubernetes.io/health-probe-path: "/healthz"    
    appgw.ingress.kubernetes.io/use-private-ip: "false"              
  name: rancher-ingress-rancher-flche-net
  namespace: cattle-system
spec:
  rules:
  - host: rancher.flche.net
    http:
      paths:
      - backend:
          service:
            name: rancher
            port:
              number: 80
        path: /
        pathType: Exact
  tls:
  - hosts:
    - rancher.flche.net
    secretName: flche-tls-secret-rancher-flche-net